[phases.setup]
nixPkgs = [
  "openjdk17",
  "maven",
  "nodejs_20"
]

[phases.build]
cmds = [
  # Build backend (tự động tìm pom.xml đúng chỗ)
  "mvn -f backend/game_tien_tri/pom.xml -B clean package -DskipTests",

  # Build frontend
  "npm --prefix frontend install",
  "npm --prefix frontend run build"
]

[start]
cmd = "java -jar backend/game_tien_tri/target/*.jar"
