[phases.setup]
nixPkgs = ["openjdk17", "maven", "nodejs_20"]

[phases.build]
cmds = [
  "mvn -f backend/game_tien_tri/pom.xml clean package -DskipTests",
  "npm --prefix frontend install",
  "npm --prefix frontend run build"
]

[start]
cmd = "java -jar backend/game_tien_tri/target/*.jar"
