[phases.setup]
nixPkgs = [
  "openjdk17",
  "maven",
  "nodejs_20"
]

[phases.build]
cmds = [
  # Build backend
  "cd backend/game_tien_tri && mvn -B clean package -DskipTests",

  # Build frontend
  "cd frontend && npm install",
  "cd frontend && npm run build"
]

[start]
cmd = "java -jar backend/game_tien_tri/target/*.jar"
