[phases.setup]
commands = [
  "echo 'Setup phase'"
]

[phases.build]
commands = [
  # Build backend Java
  "cd backend && ./mvnw clean package -DskipTests",

  # Build frontend React
  "cd frontend && npm install && npm run build"
]

[phases.deploy]
commands = [
  # Copy FE build vào BE resources/static
  "cp -r frontend/build backend/src/main/resources/static"
]

[start]
cmd = "java -jar backend/target/*.jar"

[env]
PORT = "8080"
