[phases.setup]
nixPkgs = ["openjdk17"]  # hoặc openjdk21 nếu bạn dùng Spring Boot 3.3+
commands = [
  "echo 'Setup phase'"
]

[phases.build]
commands = [
  "cd backend && ./mvnw clean package -DskipTests",
  "cd frontend && npm install && npm run build"
]

[phases.deploy]
commands = [
  "cp -r frontend/build backend/src/main/resources/static"
]

[start]
cmd = "java -jar backend/target/*.jar"

[env]
PORT = "8080"
